---
Parameters:
  User:
    Description: Current env
    Type: String
    Default: 'root'
    
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub avneet-test-${User}